<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\backend\ApplyController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\backend\FeedbackController;
use App\Http\Controllers\Backend\ProfileController;
use App\Http\Controllers\Backend\DoctorController;
use App\Http\Controllers\Backend\DoctorBannerController;
use App\Http\Controllers\Backend\AboutBannerController;
use App\Http\Controllers\Backend\AboutUsController;
use App\Http\Controllers\Backend\AdvantageController;
use App\Http\Controllers\Backend\PartnerController;
use App\Http\Controllers\Backend\ContactBannerController;
use App\Http\Controllers\Backend\ContactController;
use App\Http\Controllers\Backend\ContactUsController;
use App\Http\Controllers\Backend\SeminarBannerController;
use App\Http\Controllers\Backend\SeminarController;
use App\Http\Controllers\Backend\DepartmentController;
use App\Http\Controllers\Backend\DepartmentBannerController;
use App\Http\Controllers\Backend\BlogBannerController;
use App\Http\Controllers\Backend\BlogController;
use App\Http\Controllers\Backend\CheckupController;
use App\Http\Controllers\Backend\ServiceCategoryController;
use App\Http\Controllers\Backend\ServiceController;
use App\Http\Controllers\Backend\CheckupBannerController;
use App\Http\Controllers\Backend\CareerBannerController;
use App\Http\Controllers\Backend\CareerController;
use App\Http\Controllers\Backend\EhekimController;
use App\Http\Controllers\Backend\SocialController;
use App\Http\Controllers\Backend\DoctorSocialController;
use App\Http\Controllers\Backend\EmergencyController;
use App\Http\Controllers\Backend\FooterLogoController;
use App\Http\Controllers\Backend\HomeSeoController;
use App\Http\Controllers\Backend\DoctorSeoController;
use App\Http\Controllers\Backend\AboutSeoController;
use App\Http\Controllers\Backend\ContactSeoController;
use App\Http\Controllers\Backend\SeminarSeoController;
use App\Http\Controllers\Backend\DepartmentSeoController;
use App\Http\Controllers\Backend\BlogSeoController;
use App\Http\Controllers\Backend\LabSeoController;
use App\Http\Controllers\Backend\CheckupSeoController;
use App\Http\Controllers\Backend\CareerSeoController;
use App\Http\Controllers\Backend\EhekimSeoController;
use App\Http\Controllers\Backend\EmergencySeoController;
use App\Http\Controllers\Backend\DepartmentCategoryController;
use App\Http\Controllers\backend\TranslationController;
use App\Http\Controllers\backend\VacancyController;
use App\Http\Controllers\ContactApplyController;
use App\Http\Controllers\EhekimApplicationController;
use App\Http\Controllers\Backend\SurgeryBannerController;
use App\Http\Controllers\backend\SurgeryController;
use App\Http\Controllers\Backend\HomeBannerController;
use App\Http\Controllers\frontend\AboutController as FrontendAboutController;
use App\Http\Controllers\frontend\ContactController as FrontendContactController;
use App\Http\Controllers\frontend\DepartmentController as FrontendDepartmentController;
use App\Http\Controllers\frontend\DoctorController as FrontendDoctorController;
use App\Http\Controllers\frontend\SeminarController as FrontendSeminarController;
use App\Http\Controllers\frontend\BLogController as FrontendBLogController;
use App\Http\Controllers\SurgeryBanner;
use App\Models\Feedback;
use Illuminate\Support\Facades\Route;
use PhpParser\Node\Stmt\Label;




Route::resource('home-banner',HomeBannerController::class);
    Route::resource('doctor',DoctorController::class);
    Route::resource('doctor-banner',DoctorBannerController::class);
    Route::resource('feedback',FeedbackController::class);
    Route::resource('about-banner',AboutBannerController::class);
    Route::resource('about-us',AboutUsController::class);
    Route::resource('advantage',AdvantageController::class);
    Route::resource('partner',PartnerController::class);
    Route::resource('contact-banner',ContactBannerController::class);
    Route::resource('contact-us',ContactUsController::class);
    Route::resource('contact',ContactController::class);
    Route::resource('seminar-banner',SeminarBannerController::class);
    Route::resource('seminar',SeminarController::class);
    Route::resource('department',DepartmentController::class);
    Route::resource('department-banner',DepartmentBannerController::class);
    Route::resource('blog-banner',BlogBannerController::class);
    Route::resource('blog',BlogController::class);
    Route::resource('checkup',CheckupController::class);
    Route::resource('service-category',ServiceCategoryController::class);
    Route::resource('service',ServiceController::class);
    Route::resource('checkup-banner',CheckupBannerController::class);
    Route::resource('career-banner',CareerBannerController::class);
    Route::resource('career',CareerController::class);
    Route::resource('vacancy',VacancyController::class);
    Route::resource('e-hekim',EhekimController::class);
    Route::resource('social',SocialController::class);
    Route::resource('doctor-social',DoctorSocialController::class);
    Route::resource('emergency',EmergencyController::class);
    Route::resource('footer-logo',FooterLogoController::class);
    Route::resource('home-seo',HomeSeoController::class);
    Route::resource('doctor-seo',DoctorSeoController::class);
    Route::resource('about-seo',AboutSeoController::class);
    Route::resource('contact-seo',ContactSeoController::class);
    Route::resource('seminar-seo',SeminarSeoController::class);
    Route::resource('department-seo',DepartmentSeoController::class);
    Route::resource('blog-seo',BlogSeoController::class);
    Route::resource('lab-seo',LabSeoController::class);
    Route::resource('checkup-seo',CheckupSeoController::class);
    Route::resource('career-seo',CareerSeoController::class);
    Route::resource('e-hekim-seo',EhekimSeoController::class);
    Route::resource('e-hekim-seo',EhekimSeoController::class);
    Route::resource('emergency-seo',EmergencySeoController::class);
    Route::resource('department-category',DepartmentCategoryController::class);
    Route::resource('translation',TranslationController::class);
    Route::resource('apply',ApplyController::class);
    Route::resource('ehekim-apply',EhekimApplicationController::class);
    Route::resource('contact-apply',ContactApplyController::class);
    Route::resource('surgery-banner',SurgeryBannerController::class);
    Route::resource('surgery',SurgeryController::class);
    // Route::get('change-price', [SeminarController::class,'changePrice'])->name('change.price');

